### ISSUE TITLE
Update to tensorflow v2 (use tf.keras)

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge-keras#149]
This will require substantial updates to the parsing library and we will need to check if this will be a breaking change.

**Comment by umesh-timalsina** [comment]
Few notes on parsing to tensorflow.keras sources (v2.2.0):
1. keras.initializers for v2.0 is replicated from [`init_ops_v2.py`](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/init_ops_v2.py)
2. Preprocessing Layers [added](https://github.com/tensorflow/tensorflow/tree/v2.2.0/tensorflow/python/keras/layers/preprocessing). 
3. Non uniform import of super classes and inheritance: somtimes `Layer` is directly imported while at other times `base_layer.Layer` is used to create a `Layer subclass`.

**Comment by brollb** [comment]
Here are my thoughts:
- It would be good to follow imports from the initializers.py file to init_ops_v2 and init_ops. It will probably be a little annoying but will ensure that we actually parse the definitions for these initializers (which used to always be in the initializers.py file).
- It would be good to add them here too. It isn't necessary to add them in this PR though.
- It's not clear where this will become an issue. What is your concern here?

**Comment by umesh-timalsina** [comment]
1. Initializers can be parsed from `init_ops_v2` since we are planning to migrate to tf 2.0.
2. These layers are exported as `experimental`, but yeah, I agree, this should be added here.
3. Skulpt returns a different `bases` Array on one vs other. So, a lot of functions would either have to be refactored/ take into account the classes with seemingly same Super class, will yield different kinds of base Array.

Here is an example:
https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/layers/recurrent_v2.py#L68

If you replace this line with just `GRUCell` and change the import statement below before feeding it to skulpt, it will be uniform across the board.
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/layers/recurrent_v2.py#L32

The bases array for this file's AST for the `GRUCell` will be different not have an `id.v` attribute used heavily to determine base classes in our layer-parser.

**Comment by brollb** [comment]
Serialization should be easier with tf v2 :) https://keras.io/api/models/model_saving_apis/

**Comment by umesh-timalsina** [comment]
It might be noted that tensorflow [v2.3.0](https://github.com/deepforge-dev/deepforge/blob/master/src/visualizers/widgets/LogViewer/LogViewerWidget.js#L29) was released 5 days ago

**Comment by umesh-timalsina** [comment]
As discussed we are switching to python from skulpt for parsing. See #180.
